name: Deploy STM To Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2
  FUNCTION_NAME: stm_prerender
  GIT_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
  BUCKET_KEYS: ${{ secrets.BUCKET_KEYS }}

jobs:
  build-to-lambda:
    name: Build And Deploy lambda
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Configure git credentials
      run: |
        git config --global url.https://$GIT_TOKEN@github.com/.insteadOf https://github.com/

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ALPHA_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ALPHA_DEV }}
        aws-region: ${{ env.AWS_REGION }}

    - name: package and update lambda
      run: |
        aws s3 cp s3://$BUCKET_KEYS/keys/ ./ --recursive --sse aws:kms
        ls -la
        zip ${FUNCTION_NAME}.zip main internal_private_key
        aws lambda update-function-code --function-name ${{ env.FUNCTION_NAME }} --zip-file fileb://${FUNCTION_NAME}.zip